### ISSUE TITLE
After update to 11.0 the homeAssistant node call service stopped working

### ISSUE THREAD

**Issue by kwithus** [hassio-addons/addon-node-red#1282]
# Problem/Motivation

> (Why the issue was filed)
I updated to 11.0, after that all my HA call service nodes stopped working.

## Expected behavior

> (What you expected to happen) all nodes should work as before

## Actual behavior

> (What actually happened) The fields for domain and entity-id were empty, furthermore when I tried to solve this with a restart, afterwards I even couldn’t edit the nodes anymore. Rolling back to 10.3.4 didn’t help, as the nodes were still broken.

## Steps to reproduce

> (How can someone else make/see it happen)
I rolled back completely by restoring a complete HA Backup, after another update to 11.0 same result.
Unfortunately I couldn’t find anything in the logs

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by deltazerorsan** [comment]
@kwithus when you roll back everything is ok?

When I rolled back from 11 to 10 I had lost the calls to the services but I was able to rewrite and recover the working state.

God luck!

**Comment by kwithus** [comment]
Yes rolling back to 10 and reinstalling the defect nodes did work at the beginning, but then I tried again to update with same fault, rolling back then I even couldn’t edit or delete those nodes.
That’s the reason why I ended up with. Restoring a complete HA Backup. As I had this from the day before, it was no big deal.
However, I am not going to try 11.0.0 again ;-)

**Comment by deltazerorsan** [comment]
Yeah not me also. There are a few thing related to Time that I can fix. Will wait for news this week...

**Comment by jcbatt** [comment]
Perhaps somewhat related, or maybe a different issue, but the upgrade to 11.0 (and 11.01) has broken some call service nodes for me, particularly the ecobee "create_vacation" or "delete_vacation" call service.  The entity id uses the "name" now instead of the actual "entity id" like it used to in 10.4 and prior.  The API cannot handle the "name" and is looking for the "entity_id" which apparently not being passed.  Is there a way to change it back to the "entity id"?  There may be other APIs broken by this as well, but this is one I noticed.  Restoring to 10.4 fixes it, but only with a full Home Assistant restore (just restoring the nodered backup left all my entity names blank), and I'll stay there until we see if this is fixed.

**Comment by tlalos** [comment]
Same issue here cannot run services for home assistant!

**Comment by rickjmatthews** [comment]
Similar issue here.

The call service node is no longer correctly retrieving the domain parameters from the payload.

This is my message going into the node:

{"_msgid":"e057ff4f89af2268","payload":"{ "domain": "notify",\n "service": "echo_devices",\n "data": {\n "message": "I'm hungry. Give me some food.",\n "data": {\n "type": "announce",\n "method": "all"\n }\n }\n}","topic":"","voice":"Brian"}

... and this is the error message in the debug window "call service node is missing api "domain" property, not found in config or payload"

**Comment by sinclairpaul** [comment]
See #1287 ?

**Comment by jcbatt** [comment]
Between 11.02 and the update to the websocket node here, all seems to be back to normal for me. 
 https://github.com/zachowj/node-red-contrib-home-assistant-websocket/releases

**Comment by frenck** [comment]
Fixed in https://github.com/hassio-addons/addon-node-red/releases/tag/v11.0.3

**Comment by mattivoxy** [comment]
Is this actually fixed? I'm on 11.0.3 and still getting: "Call-service error. must contain at least one of temperature, target_temp_high, target_temp_low." when sending this msg.payload to my call service node for my ecobee: "{"data": {"target_temp_high": "77","target_temp_low": "70"}}"
